version: '3'

services:
  mediawiki:
    build:
      context: .
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php

  database:
    image: mariadb
    environment:
      MYSQL_DATABASE: mediawiki
      MYSQL_USER: mediawiki
      MYSQL_PASSWORD: mediawiki
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
      - ./sql/init_1_31.sql:/docker-entrypoint-initdb.d/init_1_31.sql

volumes:
  database:
